Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -72,19 +72,114 @@ jobs:
             -Dsonar.host.url=http://localhost:9000 \
             -Dsonar.login=${{ env.SONAR_TOKEN }}
             
-      - name: API component navigation
+      - name: API Testing
         env:
           SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
         run: |
           set -euo pipefail
           AUTH="Authorization: Basic $(echo -n ${SONAR_TOKEN}: | base64 -w0)"
-          url="http://localhost:9000/api/navigation/component?component=dummy.project"
           code=$(curl -s -H "$AUTH" -o /dev/null -w "%{http_code}" "$url")
-          
+
+          #/api/navigation/component?component=
+          url="http://localhost:9000/api/navigation/component?component=dummy.project"
           if (( code >= 400 && code < 600 )); then
             echo "Error in $url (HTTP $code)"
             exit 1
           fi
           echo "$url OK (HTTP $code)"
 
-          
+          #/api/measures/component?metricKeys=reliability_rating,software_quality_maintainability_rating,security_rating,security_review_rating&component=
+          url="http://localhost:9000/api/measures/component?metricKeys=reliability_rating,software_quality_maintainability_rating,security_rating,security_review_rating&component=dummy.project"
+          if (( code >= 400 && code < 600 )); then
+            echo "Error in $url (HTTP $code)"
+            exit 1
+          fi
+          echo "$url OK (HTTP $code)"
+
+          #/api/qualitygates/project_status?projectKey=
+          url="http://localhost:9000/api/qualitygates/project_status?projectKey=dummy.project"
+          if (( code >= 400 && code < 600 )); then
+            echo "Error in $url (HTTP $code)"
+            exit 1
+          fi
+          echo "$url OK (HTTP $code)"
+
+          #/api/measures/component?metricKeys=duplicated_lines_density,comment_lines_density,ncloc,complexity,cognitive_complexity,coverage&component=
+          url="http://localhost:9000/api/measures/component?metricKeys=duplicated_lines_density,comment_lines_density,ncloc,complexity,cognitive_complexity,coverage&component=dummy.project"
+          if (( code >= 400 && code < 600 )); then
+            echo "Error in $url (HTTP $code)"
+            exit 1
+          fi
+          echo "$url OK (HTTP $code)"
+
+          #/api/measures/component?metricKeys=duplicated_lines_density,comment_lines_density,ncloc,complexity,cognitive_complexity,coverage&component=
+          url="http://localhost:9000/api/measures/component?metricKeys=duplicated_lines_density,comment_lines_density,ncloc,complexity,cognitive_complexity,coverage&component=dummy.project"
+          if (( code >= 400 && code < 600 )); then
+            echo "Error in $url (HTTP $code)"
+            exit 1
+          fi
+          echo "$url OK (HTTP $code)"
+
+          #/api/measures/component?metricKeys=reliability_remediation_effort,security_remediation_effort,sqale_index&component=
+          url="http://localhost:9000/api/measures/component?metricKeys=reliability_remediation_effort,security_remediation_effort,sqale_index&component=dummy.project"
+          if (( code >= 400 && code < 600 )); then
+            echo "Error in $url (HTTP $code)"
+            exit 1
+          fi
+          echo "$url OK (HTTP $code)"
+
+          #/api/measures/component?metricKeys=ncloc_language_distribution&component=
+          url="http://localhost:9000/api/measures/component?metricKeys=ncloc_language_distribution&component=dummy.project"
+          if (( code >= 400 && code < 600 )); then
+            echo "Error in $url (HTTP $code)"
+            exit 1
+          fi
+          echo "$url OK (HTTP $code)"
+
+          #/api/security_reports/show?standard=sonarsourceSecurity&project=
+          url="http://localhost:9000/api/security_reports/show?standard=sonarsourceSecurity&project=dummy.project"
+          if (( code >= 400 && code < 600 )); then
+            echo "Error in $url (HTTP $code)"
+            exit 1
+          fi
+          echo "$url OK (HTTP $code)"
+
+          #/api/hotspots/search?status=TO_REVIEW&ps=500&pageIndex=%d&project=
+          url="http://localhost:9000/api/hotspots/search?status=TO_REVIEW&ps=500&pageIndex=%d&project=dummy.project"
+          if (( code >= 400 && code < 600 )); then
+            echo "Error in $url (HTTP $code)"
+            exit 1
+          fi
+          echo "$url OK (HTTP $code)"
+
+          #/api/issues/search?types=BUG&facets=severities&componentKeys=
+          url="http://localhost:9000/api/issues/search?types=BUG&facets=severities&componentKeys=dummy.project"
+          if (( code >= 400 && code < 600 )); then
+            echo "Error in $url (HTTP $code)"
+            exit 1
+          fi
+          echo "$url OK (HTTP $code)"
+
+          #/api/issues/search?types=VULNERABILITY&facets=severities&componentKeys=
+          url="http://localhost:9000/api/issues/search?types=VULNERABILITY&facets=severities&componentKeys=dummy.project"
+          if (( code >= 400 && code < 600 )); then
+            echo "Error in $url (HTTP $code)"
+            exit 1
+          fi
+          echo "$url OK (HTTP $code)"
+
+          #/api/issues/search?types=CODE_SMELL&facets=severities&componentKeys=
+          url="http://localhost:9000/api/issues/search?types=CODE_SMELL&facets=severities&componentKeys=dummy.project"
+          if (( code >= 400 && code < 600 )); then
+            echo "Error in $url (HTTP $code)"
+            exit 1
+          fi
+          echo "$url OK (HTTP $code)"
+
+          #/api/issues/search?issueStatuses=OPEN&ps=500&pageIndex=%d&componentKeys=
+          url="http://localhost:9000/api/issues/search?issueStatuses=OPEN&ps=500&pageIndex=%d&componentKeys=dummy.project"
+          if (( code >= 400 && code < 600 )); then
+            echo "Error in $url (HTTP $code)"
+            exit 1
+          fi
+          echo "$url OK (HTTP $code)"
